
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjpwajipuwkuoyhconlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqcHdhamlwdXdrdW95aGNvbmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTQ0NTIsImV4cCI6MjA2MjQ3MDQ1Mn0.09xudlK8w5Rp-yBDxv3lJn5UMGKzBzjNeymm8WmCoD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
